spring.datasource.url: jdbc:h2:file:./camunda-h2-database

spring:
  jersey:
    application-path: engine-rest
camunda.bpm:
  authorization:
    enabled: true
  admin-user:
    id: demo
    password: demo

jwt.auth.user: user
jwt.auth.password: $2a$10$slYQmyNdGzTn7ZLBXBChFOC9f6kFjAqPhccnP6DxlWXx2lPk1C3G6

jwt.secret: 2dae84f846e4f4b158a8d26681707f4338495bc7ab68151d7f7679cc5e56202dd3da0d356da007a7c28cb0b780418f4f3246769972d6feaa8f610c7d1e7ecf6a
jwt.get.token.uri: /authenticate
jwt.token.validity: 300

logging.level.com.example.workflow: DEBUG